# Generated by Django 2.2.4 on 2019-09-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypedAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tmodels.canine', 'canine'), ('tmodels.feline', 'feline')], db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=200, null=True)),
                ('mice_eaten', models.IntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Canine',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tmodels.typedanimal',),
        ),
        migrations.CreateModel(
            name='Feline',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tmodels.typedanimal',),
        ),
    ]
